### ISSUE TITLE
package for pip: sipyco and newfocus8742

### ISSUE THREAD

**Issue by lbusoni** [ArcetriAdaptiveOptics/plico_motor_server#1]
sipyco and newfocus8742 are not properly packaged in pypi (maybe they are in conda?)
for installation via python setup.py the dependence like  

`sipyco @ git+https://github.com/m-labs/sipyco.git`

is valid and plico_motor_server properly installs (also from local with pip install -e .)

But when I try to upload on pip I get:

_Invalid value for requires_dist. Error: Can't have direct dependency: 'sipyco @ git+https://github.com/m-labs/sipyco.git'_

I can of course remove the direct dependence and package plico_motor_server as if sipyco and newfocus8742 were available on pip, but then plico_motor_server cannot be  installed anyhow, so it doesn't really help.

Should we go back and re-add sipyco and newfocus8742 as external submodules? It doesn't really solve the issue of pip-installing them... Or maybe yes, by properly modifying our setup.py to install both our code and the submodules one, skipping the submodules's setup.py?

**Comment by alfiopuglisi** [comment]
newfocus8742 is on conda (in a non-default channel: https://anaconda.org/quartiq/repo ), but sipyco is not (quartiq split the sipyco module out from their main code, but did not add it to conda or anywhere else...).
I think that the only way is it to add them as submodules, maybe with a specific version, and modify setup.py to install them. It should be possible to do it automatically with setuptools.find_packages()

**Comment by lbusoni** [comment]
This was solved in 151e1143595747a17862fe1c9b8129936b1e8fef by reimplementing the communication with the newfocus8742 without the need of  external dependencies
