### ISSUE TITLE
USB discovery

### ISSUE THREAD

**Issue by lbusoni** [ArcetriAdaptiveOptics/plico_motor_server#6]
Find a way of addressing USB devices by name (and refer to names in the conf file) instead of tty/USB devices whose indexing depends on external factors, including the order the devices are plugged into the ports

**Comment by lbusoni** [comment]
This is actually more for plico than for plico_motor_server

**Comment by alfiopuglisi** [comment]
This is now included in the main plico package in plico/utils/serial_or_usb_connection.py
